### ISSUE TITLE
"Starcounter Application" project is created with wrong StarcounterVersionCompatibility

### ISSUE THREAD

**Issue by joozek78** [Starcounter/Starcounter.VisualStudio#5]
Starcounter version: 2.4.0.1566

In VS select create new project from template "Starcounter Application". It fails to build, because it has StarcounterVersionCompatibility set to "2.3"

**Comment by per-samuelsson** [comment]
@joozek78 

Did you install the extension using that said build, i.e. first uninstalling it, the reinstalling it using the `.vsix` file part of the distribution? If not, you have to.

Futhermore, to use the extension with 2.4 right now require you to install it like that, since the VS Marketplace for some reason can only support a single version of every extension to exist, and we need that to be the 2.3-compatible one. I've written about that [here](https://github.com/Starcounter/Starcounter.VisualStudio/wiki/Version-compatibility#i-cant-find-version-2x-of-the-extension-on-the-visual-studio-marketplace).

**Comment by per-samuelsson** [comment]
BTW, 2.4 is really in a state where you can't expect everything to work smoothly ATM. It's very much bleeding edge. But we are about to give it some love some time soon, starting with some meeting already tomorrow if I remember correctly.

**Comment by joozek78** [comment]
I confirm, after reinstalling VSIX it works
